### PR TITLE
feat: add json support

### PR DESCRIPTION
**Pull request by groobyming**
Add support for trino json data type, trino json data type reference is based on
https://trino.io/docs/current/language/types.html#json

### CODE REVIEW

**Comment by groobyming** [comment]
@nooberfsh.  😀  Please take a look if you have time, Thanks a lot.

**Comment by nooberfsh** [comment]
Thanks for the PR.
Please fix the warnings in the PR.

**Comment by groobyming** [comment]
> Thanks for the PR. Please fix the warnings in the PR.

Ok

**Comment by groobyming** [comment]
> Thanks for the PR. Please fix the warnings in the PR.

Fixed the clippy warnings

**Comment by nooberfsh** [comment]
Thank you!

**Pull request merged**
